export const PALETTES = [
  {
    id: 'campos',
    name: 'Campos',
    line: 'La del sitio. Crema, bosque y petróleo.',
    cream: '#F4EFE6',
    creamDeep: '#EBE4D4',
    forest: '#1E4A32',
    petroleum: '#0B4F6C',
    petroleumDeep: '#083D54',
    ink: '#1A2A22',
    creamName: 'Crema',
    forestName: 'Bosque',
    petroleumName: 'Petróleo',
    inkName: 'Tinta',
  },
  {
    id: 'clara',
    name: 'Clara',
    line: 'Papel, salvia y arena. Las tres claras.',
    cream: '#F6F0E6',
    creamDeep: '#EBE3D4',
    forest: '#C5D5C2',
    petroleum: '#E4C2A4',
    petroleumDeep: '#D4B090',
    ink: '#2A332C',
    onDark: '#2A332C',
    creamName: 'Papel',
    forestName: 'Salvia',
    petroleumName: 'Arena',
    inkName: 'Tinta',
  },
  {
    id: 'sol',
    name: 'Sol',
    line: 'Mantequilla, girasol y mango. Sin negro.',
    cream: '#FFF6D4',
    creamDeep: '#FFE9A0',
    forest: '#FFD84A',
    petroleum: '#F5A34A',
    petroleumDeep: '#E8923A',
    ink: '#3E2E0C',
    onDark: '#3E2E0C',
    creamName: 'Mantequilla',
    forestName: 'Girasol',
    petroleumName: 'Mango',
    inkName: 'Tinta',
  },
  {
    id: 'violeta',
    name: 'Violeta',
    line: 'Lila, violeta y turquesa, en el mismo tono.',
    cream: '#F5F1FB',
    creamDeep: '#E6DCF6',
    forest: '#CDBBEA',
    petroleum: '#A8DDD6',
    petroleumDeep: '#8FCFC6',
    ink: '#2C2440',
    onDark: '#2C2440',
    creamName: 'Lila',
    forestName: 'Violeta',
    petroleumName: 'Turquesa',
    inkName: 'Tinta',
  },
  {
    id: 'jardin',
    name: 'Jardín',
    line: 'Lino, pétalo y hoja.',
    cream: '#FBF7F4',
    creamDeep: '#F3E6E0',
    forest: '#F3C3CF',
    petroleum: '#A3C98E',
    petroleumDeep: '#8FB87A',
    ink: '#2A241C',
    onDark: '#2A241C',
    creamName: 'Lino',
    forestName: 'Pétalo',
    petroleumName: 'Hoja',
    inkName: 'Tinta',
  },
  {
    id: 'nube',
    name: 'Nube',
    line: 'Nube, añil y durazno.',
    cream: '#F4F6FB',
    creamDeep: '#E4E8F6',
    forest: '#C5CEF5',
    petroleum: '#F6C09A',
    petroleumDeep: '#E8A87A',
    ink: '#1E2438',
    onDark: '#1E2438',
    creamName: 'Nube',
    forestName: 'Añil',
    petroleumName: 'Durazno',
    inkName: 'Tinta',
  },
  {
    id: 'noche',
    name: 'Noche',
    line: 'Lila, mora y turquesa. Las placas oscuras.',
    cream: '#F4F0FA',
    creamDeep: '#E6DCF4',
    forest: '#3E2770',
    petroleum: '#0F6468',
    petroleumDeep: '#0B4C50',
    ink: '#1A1228',
    creamName: 'Lila',
    forestName: 'Mora',
    petroleumName: 'Turquesa',
    inkName: 'Tinta',
  },
] as const;

export type PaletteId = (typeof PALETTES)[number]['id'];
